/*******************************************************************************
 * maze.h - Maze model, rendering and collision for the Maze game.
 *
 * The maze is an 8x8 grid of cells (12 px pitch) on the 96x96 OLED. Walls live
 * on cell edges and are stored two ways:
 *   - logical wall arrays (vwall/hwall)         -> generation + solvability
 *   - a 96x96 1-bit occupancy bitmap (rasterized) -> fast pixel collision
 *
 * The maze is generated by a deterministic recursive-backtracker, so a fixed
 * seed yields a fixed, fair, guaranteed-solvable maze with many dead ends.
 ******************************************************************************/
#ifndef MAZE_H
#define MAZE_H

#include <stdint.h>
#include <stdbool.h>
#include "game_config.h"

/* Build the maze (walls + collision bitmap) from a deterministic seed. */
void maze_generate(uint32_t seed);

/* Draw the whole maze (walls + start/finish markers) to the OLED. */
void maze_render(void);

/* Redraw just the start and finish markers (call after erasing the ball). */
void maze_draw_markers(void);

/* True if pixel (x,y) is a wall (or outside the panel). */
bool maze_is_wall_px(int x, int y);

/* True if a ball of radius r centered at (cx,cy) hits a wall or the bounds. */
bool maze_ball_collides(int cx, int cy, int r);

/* Center pixel of the start / finish cells. */
void maze_start_pixel(int *x, int *y);
void maze_finish_pixel(int *x, int *y);

/* True if (cx,cy) lies inside the finish cell. */
bool maze_at_finish(int cx, int cy);

/* Logical wall accessors (used by validation / tests). */
bool maze_vwall(int row, int col);   /* wall on left edge of cell (col,row) */
bool maze_hwall(int row, int col);   /* wall on top  edge of cell (col,row) */

#endif /* MAZE_H */
